Feature/login function (fixes #9 #14)
Mentalist-Group/premind pull request #15
Opened 2020-01-20 18:19 UTC by nakajima1412

ログイン処理の実装しました。
* larabelにAPI通信で認証
* 空文字のときにエラーメッセージ表示

画面デザインは次回修正します

2020-01-23 06:00 UTC, nakajima1412 commented
すみません、vuetifyを使ってログインページをマテリアルデザインにしたので確認お願い致します。
ページが大きくなりすぎたので、今後コンポーネントに分割します、、、

2020-01-23 11:03 UTC, Mitsuhiro0911 requested changes
ユーザ登録の処理について１点指摘があります。
DB登録時はパスワードが8文字未満を不整値としているのに対し、
画面入力時のバリデーションでは4文字未満が不整値となっています。
画面入力時の不正値の条件を、DB登録時と同じ8文字未満で統一するよう、お願いします。

2020-01-23 12:57 UTC, nakajima1412 commented
8文字未満の根拠は`src/app/Http/Controllers/Auth/RegisterController.php`ということでいいかな？
`src/resources/js/pages/Login.vue/`を下のように変えます

```diff
<VTextFieldWithValidation
                    id="login-password"
                    v-model="loginForm.password"
                    label="Password"
-                    rules="required|min:4"
+                   rules="required|min:8"
                    prepend-icon="lock"
                  />
```

2020-01-25 04:20 UTC, Mitsuhiro0911 approved these changes
OKです。

2020-01-25 04:20 UTC, Mitsuhiro0911 commented on src/resources/js/pages/Login.vue
> +                    rules="required|min:4"
min:8に変更してください

2020-01-25 04:20 UTC, Mitsuhiro0911 commented on src/resources/js/pages/Login.vue
> +                    rules="required|min:4"
min8に変更してください

2020-01-25 04:20 UTC, Mitsuhiro0911 commented on src/resources/js/pages/Login.vue
> +                    rules="required|min:4"
min:8に変更してください

2020-01-25 04:20 UTC, merged